### ISSUE TITLE
Portal - Admin User Search

### ISSUE THREAD

**Issue by ckelch** [iwu/iwu-website#39] opened 2015-11-12 15:44 UTC
Would like to have an interface to search for users. Search should be able to search for students, staff, faculty, and alumni. Should report a user’s first, last, and preferred name. Other details include role, birthdate, major, ID#, last 4 of SSN. Can this data come from AD? If can't be done, we will have to start using Banner instead of MyIWU for this.

**Comment by michaelcgorman** [comment] 2015-11-12 15:59
Duplicate of #13.

**Closed by michaelcgorman** 2015-11-12 15:59 UTC
